public class PersonWrapper {
    /*public String name ;
    public Integer age ;
    public Boolean married ;
    public Double height ;

    // Constructor
    public void  PersonWrappermethod(String PersonName, Integer PersonAge, Boolean marriedStatus, Double PersonHeight) {
		name = PersonName ;
        age = PersonAge ;
        married = marriedStatus ;
        height = PersonHeight ;
    } 

    // Method to return combined data
    public String getCombinedData() {
        return 'Name: ' + name + ', Age: ' + age + ', Married: ' + (married ? 'Yes' : 'No') + ', Height: ' + height + ' meters';
    }*/
}